#!/bin/bash
#shellcheck disable=SC2155,SC1091
# Whatlang wrapper script
set -euo pipefail

# Get script path
declare -- PRG0=$(readlink -en -- "$0")
declare -- PRGDIR=$(dirname -- "$PRG0") PRG=$(basename -- "$PRG0")

# Activate virtualenv and run
source "$PRGDIR"/.venv/bin/activate
"$PRGDIR"/.venv/bin/python "$PRGDIR"/whatlang.py "$@"
#fin