#!/bin/bash
#shellcheck disable=SC2155,SC1091
# Whatlang - CLI wrapper for language detection
set -euo pipefail

# Resolve script location
declare -- PRG0=$(readlink -en -- "$0")
declare -- PRGDIR=$(dirname -- "$PRG0") PRG=$(basename -- "$PRG0")

# Run implementation in virtualenv
source "$PRGDIR"/.venv/bin/activate
"$PRGDIR"/.venv/bin/python "$PRGDIR"/whatlang.py "$@"
#fin